name: Docker Image Check

on:
  push:
    branches: ["develop", "main"]
  workflow_dispatch:

jobs:
  docker-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-satc:0.0.1 .

      - name: Push Docker Image
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/devops-satc:0.0.1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Matheus2037_devops-satc
            -Dsonar.organization=matheus2037
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/devops-satc:0.0.1'
          format: json
          output: trivy-results.json
          severity: MEDIUM,HIGH,CRITICAL

      - name: Upload Trivy results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results.json
          path: trivy-results.json

      - name: Analyze Trivy results
        run: |
          if [ -f trivy-results.json ]; then
            VULN_COUNT_MEDIUM=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "MEDIUM")] | length' trivy-results.json)
            echo "Quantidade de vulnerabilidades médias: $VULN_COUNT_MEDIUM"
          fi
          if [ -f trivy-results.json ]; then
            VULN_COUNT_HIGH=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' trivy-results.json)
            echo "Quantidade de vulnerabilidades altas: $VULN_COUNT_HIGH"
          fi

          if [ "$VULN_COUNT_MEDIUM" -gt 50 ]; then
             echo "Pipeline bloqueada: mais de 50 vulnerabilidades médias encontradas."
             exit 1
           fi
          if [ "$VULN_COUNT_HIGH" -gt 50 ]; then
             echo "Pipeline bloqueada: mais de 50 vulnerabilidades altas encontradas."
             exit 1
           fi
          
      - name: Falhar se houver mais de 2 vulnerabilidades médias
        run: |
          COUNT=$(curl -s -u "${SONAR_TOKEN}:" \
            "https://sonarcloud.io/api/issues/search?componentKeys=${SONAR_PROJECT_KEY}&types=VULNERABILITY&severities=MAJOR&resolved=false&ps=1" \
            | jq '.total')

          echo "Quantidade de vulnerabilidades médias reportadas pelo Sonar: $COUNT"

          if [ "$COUNT" -gt 2 ]; then
            echo "Pipeline bloqueada: mais de 2 vulnerabilidades médias encontradas no Sonar."
            exit 1
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_PROJECT_KEY: Matheus2037_devops-satc